theme: jekyll-theme-primer
title: Report
description: Murder Rate Predictive Analysis - Team 14 
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
